---
title: "R Project 1 - Hello R"
author: "Cameron Brown"
date: "Due Sept 8th"
output: 
  html_document: 
    fig_width: 8
    fig_height: 7
    highlight: monochrome
---

MAKE SURE YOU READ AND FOLLOW **ALL** INSTRUCTIONS ON THE INSTRUCTION DOCUMENT. 

### Load packages

```{r load-packages, message=FALSE}
library(tidyverse) 
library(datasauRus)
```


### Exercise 1

> "1846 rows with 3 variables"

### Exercise 2

```{r plot-dino, fig.height=3, fig.width=6}
dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")
ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
  geom_point()
```

```{r cor-dino}
dino_data %>%
  summarize(r = cor(x, y))
```

### Exercise 3

```{r plot-star}
star_data <- datasaurus_dozen %>%
  filter(dataset == "star")
ggplot(data = star_data, mapping = aes(x = x, y = y)) +
  geom_point()
```


Calculate the correlation between 'x' and 'y' for star dataset.
 
 
```{r cor-star}
star_data %>%
  summarize(r = cor(x, y))
```

### Exercise 4


```{r plot-circle}
circle_data <- datasaurus_dozen %>%
  filter(dataset == "circle")
ggplot(data = circle_data, mapping = aes(x = x, y = y)) +
  geom_point()


```

```{r cor-circle}
circle_data %>%
  summarize(r = cor(x, y))

```

### Exercise 5

``` {r}
ggplot(datasaurus_dozen, aes(x = x, y = y, color = dataset))+
geom_point()+
facet_wrap(~ dataset, ncol = 3) + # facet the dataset variable, in 3 cols
theme(legend.position = "none")
```

```{r}
datasaurus_dozen %>%
group_by(dataset) %>%
summarize(r = cor(x, y)) %>%
print(26)
```